site_name: fastapi-docx
site_description: Extend a FastAPI OpenAPI spec to include HTTPException or custom Exception response schemas.
strict: true
site_url: https://github.com/Saran33/fastapi-docx

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: Saran33/fastapi-docx
repo_url: https://github.com/Saran33/fastapi-docx
edit_uri: ''
plugins:
- search
nav:
- fastapi-docx: index.md
- Getting Started: getting-started.md
- HTTPException Responses:
  - find-exception-responses/overview.md
  - Dependency or Service Classes: find-exception-responses/dependency-or-service-classes.md
- Custom Exception Responses: custom-exceptions/index.md
- Response Schemas: response-schemas/index.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/Saran33/fastapi-docx
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
