name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-docs:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ github.ref }}
      - name: Install docs dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make -e poetry-install-flags='--only docs' venv-install
          make coverage-badge
          make deploy-docs
