name: Tests

on: push

env:
  PRE_COMMIT_COLOR: "always"

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: ./.github/actions/setup-python
      - run: make venv-install
      - run: make mypy
      - run: make pre-commit-run

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: ./.github/actions/setup-python
      - run: make venv-install
      - run: make unit-tests-with-cov
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage_report
      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage_report

  deploy-docs:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ github.ref }}
      - name: Install docs dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make -e poetry-install-flags='--only docs' venv-install
          make coverage-badge
          make deploy-docs
