name: CI

on: push

env:
  PRE_COMMIT_COLOR: "always"

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: ./.github/actions/setup-python
      - run: make venv-install
      - run: make mypy
      - run: make pre-commit-run

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: ./.github/actions/setup-python
      - run: make venv-install
      - run: make unit-tests-with-cov
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage_report

  deploy-docs:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: ./.github/actions/setup-python
        with:
          python_version: "3.10"
      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage_report
      - uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ github.ref }}
      - name: Install docs dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make -e poetry-install-flags='--only docs' venv-install
      - name: Create coverage badge
        run: make coverage-badge
      - name: Deploy docs
        run: make deploy-docs
